//------------------------------------------------------------------------------
// <auto-generated>
//     Gerado pelo Visual Studio. Alterações manuais serão perdidas.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegacyShop.Web.Relatorios
{
    public partial class Vendas
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.DropDownList ddlMes;
        protected global::System.Web.UI.WebControls.GridView gvVendas;
        protected global::System.Web.UI.WebControls.Button btnExportar;
    }
}
